apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-rolebinding
  namespace: nginx-ns
subjects:
- kind: ServiceAccount
  name: nginx-sa
  namespace: nginx-ns
roleRef:
  kind: Role
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io